## Numpy Version

In [6]:
import numpy as np
import pandas as pd

In [4]:
np.__version__ 

'1.19.2'

In [8]:
pd.__version__

'1.1.5'

### ndarray 생성

In [9]:
arr = np.array([1,2,3,4], dtype=int)

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(4,)

In [13]:
# 1차원 리스트
myList = [1,2,3,4]  #python List
arr = np.array(myList, dtype=float)

In [14]:
arr

array([1., 2., 3., 4.])

In [15]:
# 퀴즈
myList = [1.3, 2.3, 3.3, 4.3]
arr = np.array(myList, dtype=int)

In [16]:
arr

array([1, 2, 3, 4])

In [17]:
myList2 = [[1,2,3,4],
           [5,6,7,8]]

In [22]:
myList2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr = np.array(myList2)

In [24]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
myList = [1, 3.14, 'hello', '1234']

In [30]:
myList

[1, 3.14, 'hello', '1234']

In [31]:
arr = np.array(myList)

In [32]:
arr

array(['1', '3.14', 'hello', '1234'], dtype='<U32')

In [33]:
arr[0]+arr[1]

'13.14'

In [35]:
float(arr[0])+float(arr[1])

4.140000000000001

## 슬라이싱(Slicing)

배열을 부분 선택

#### 1차원 배열의 부분 선택

In [37]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr.shape

(10,)

In [38]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [39]:
arr[-1]

9

In [40]:
arr[-10]

0

In [41]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 배열의 부분 선택

In [43]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [44]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
# np.arange(12) : 시작값 0부터 , 종료값 12미만
# np.arange(1,13) : 시작값 1부터, 종료값 13미만
arr2d = np.array(np.arange(1,13)).reshape(3,4)

In [51]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr2d[0,2]

3

In [53]:
arr2d[2,2]

11

In [54]:
arr1d = np.array(np.arange(1,13))

In [55]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
# 2~12까지만
# 시작값:종료값(생략하면 끝까지)
arr1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
# 시작값(이상):종료값(index미만)
arr1d[1:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr1d[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
arr1d[:-3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# 2차원 배열의 슬라이싱
arr2d = np.array(np.arange(1,13)).reshape(3,4)

In [62]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
# 1행을 지정한 뒤 모두 가져오기
# [행,열(: 모든 열)]
arr2d[1,:]

array([5, 6, 7, 8])

In [65]:
arr2d[1,:].shape

(4,)

In [66]:
arr2d[:,2]

array([ 3,  7, 11])

In [74]:
arr2d[:2,1:3]

array([[2, 3],
       [6, 7]])

In [76]:
# 5x5 배열, 1부터 25까지
my2dArr = np.array(np.arange(1,26)).reshape(5,5)

In [77]:
my2dArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
my2dArr[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

## Fancy Indexing

범위가 아닌 특정 index값을 선택해서 추출하고 싶을 때

In [79]:
# 1차원의 fancy indexing
myArr = np.array(np.arange(1,10))

In [80]:
myArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
idx = [0, 2, 4]

In [82]:
myArr[idx]

array([1, 3, 5])

In [84]:
# 1차원의 fancy indexing
my2dArr = np.array(np.arange(1,13)).reshape(3,4)
my2dArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
index = [0,2,3]

In [89]:
my2dArr[:2,index]

array([[1, 3, 4],
       [5, 7, 8]])

### Boolean Indexing

조건 필터링을 통해서 Boolean값을 이용한 색인

In [90]:
arr = np.array(np.arange(1,8))

In [91]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
arr2d = np.array(np.arange(1,13)).reshape(3,4)

In [94]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
myTrueFalse = [True, False, True, False, False, False, False]

In [104]:
TrueFalse = np.array(myTrueFalse)

In [105]:
arr[TrueFalse]

array([1, 3])

In [106]:
myTrueFalse = [[True, False, True, False],[True, False, True, False],[False, False, False, False]]

In [107]:
TrueFalse = np.array(myTrueFalse)

In [108]:
arr2d[TrueFalse]

array([1, 3, 5, 7])

In [113]:
# 조건 필터
TrueFalse = arr2d > 2

In [114]:
TrueFalse

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [115]:
arr2d[TrueFalse]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [116]:
arr2d[arr2d > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [117]:
arr2d[arr2d < 5]

array([1, 2, 3, 4])

### arange란?

arange = array + range

In [118]:
arr = [1,2,3,4,5,6,7,8,9,10]

In [119]:
# start(이상), stop(미만)
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
# 키워드를 사용해서 순서 없이
arr = np.arange(stop=11, start=1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
# (start, stop. step)
# 홀수만 생성
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [128]:
arr = np.arange(start=1, step=2, stop=11)
arr

array([1, 3, 5, 7, 9])


### range (numpy와는 상관없는 python 문법)

In [129]:
# range는 조건을 말할 뿐 아직 숫자가 생성X
test = range(1,11)
print(test)

range(1, 11)


In [130]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [131]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


### 1차원 정렬

In [132]:
arr = np.array([1,10,5,8,2,4,3,6,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [133]:
np.sort(arr) # 정렬만할 뿐 값을 바꾸지는 않는다.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [138]:
mySort = np.sort(arr)
mySort

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
#내림차순 정렬일 경우 옵션값에 -1을 지정한다.
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [142]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1],
                 [10,9,12,11]])

In [143]:
arr2d.shape

(3, 4)

In [144]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [149]:
# axis는 축이 행인지 열인지 가리킨다.
# axis=1 하면 같은 행 안에서 정렬이 된다.
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [148]:
# axis=0 하면 같은 열 안에서 정렬이 된다.
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

### Index를 반환하는 argsort

In [150]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1],
                 [10,9,12,11]])
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [151]:
# 열 정렬(왼쪽에서 오른쪽으로)
# argsort를 통해 출력되는 배열의 데이터는 index값을 의미
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

### numpy를 이용한 행렬 연산

In [155]:
a = np.array([[1,2,3], 
             [2,3,4]])

In [154]:
b = np.array([[1,2], 
             [3,4],
             [5,6]])

In [156]:
a+b # shape 달라서 오류

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [158]:
# np.sum
a = np.array(np.arange(1,26)).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [160]:
# 같은 열데이터 간 더하기
np.sum(a,axis=0)

array([55, 60, 65, 70, 75])

In [161]:
# 같은 행데이터 간 더하기
np.sum(a,axis=1)

array([ 15,  40,  65,  90, 115])

In [162]:
# 행렬의 뺄셈은 생략

In [163]:
# 행렬의 곱셈
a = np.array([[1,2,3], 
             [2,3,4]])

In [169]:
b = np.array([[1,2,3], 
             [4,5,6]])

In [170]:
a.shape, b.shape

((2, 3), (2, 3))

In [171]:
# 아다마르 곱
a*b

array([[ 1,  4,  9],
       [ 8, 15, 24]])

In [186]:
a = np.array(np.arange(1,10)).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [187]:
b = np.array(np.arange(1,7)).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
a.shape, b.shape

((3, 3), (3, 2))

In [189]:
# 행렬의 곱셈
np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [190]:
# 행렬의 곱셈 표현2
a.dot(b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

### Broadcasting

In [194]:
a = np.array([[1,2,3], 
             [2,3,4]])

In [195]:
b = np.array([[3,3,3], 
             [3,3,3]])

In [196]:
a+b

array([[4, 5, 6],
       [5, 6, 7]])

In [197]:
# broadcasting 연산
a+3

array([[4, 5, 6],
       [5, 6, 7]])

In [198]:
a-3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [199]:
# 아다마르 곱
a*3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [200]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

In [201]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [202]:
b = np.array([[1],[2]])

In [203]:
a.shape, b.shape

((2, 3), (2, 1))

In [204]:
# 행 단위로 broadcasting 연산
a*b

array([[1, 2, 3],
       [4, 6, 8]])

In [205]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [206]:
b = np.array([1,2,3])

In [207]:
# 열 단위로 broadcasting 연산
a*b

array([[ 1,  4,  9],
       [ 2,  6, 12]])